export const ICONS: string[] = [
  'add',
  'compass',
  'discord',
  'download',
  'settings',
  'triangle-left',
  'microphone',
  'muted-microphone',
  'audio',
  'muted-audio',
  'online',
  'idle',
  'do-not-disturb',
  'invisible',
];
